travis:
  secure:
    BINSTAR_TOKEN: gA28ibKckFV50BKyBHAEmgp2VgNsrzapGfIFkIjMpYRgWMQJGeixfDHVntZheYFmnAyKDx46y/+FAcEwgD9ctp2xjiHPB12znznTz3aAFe5C+uzs9Q/OE9GIOWHKq3V6XWYXwCS+QzKK6Z+LGO3yl/14xAgGt4pePDgSTHvGoASNYK3dKn0wgauQJHkc10vZnpPzYn2PpGSm1bXIseaVoMwiNu8OZ3Zv+TUqu2S09U+DPMWfEIgvAril3qrD8HBiPjSzF8wv/oj1NNwJ0gncIIWTO6YlPiClVKNxGK78+O4mrM4whSOEN7QTa4cSuU7wkFeOPwpYHlyemWpk+pqhD3PVYYtCt14XHZyrPpzB7UCrV4s250306nN/0ZxtVj4aV16sofN81sfyMUrQ3z54IsMIuUSkeu3bvM6uWLs2PiGvgn1uoui2Vssp+ugcPPYRc0tmRnb5TR9WHgwvFOeUMMPrLT5ENGHPqfZVzBU9wKayfAMLD2PEmlGyezU+LfzT1AGO18qgtCf9AL6EkjDmGhByORzXEaiij6ZqRUVglNOi/rSJhGkehCt+vNE1Xd/03ICzbecxm86MkMZkevGaI+zAIIdoFMzi5boAhBlSOaKoPBYclEbBfOAhwTqB+p8yNxKjHFiaGP70PbdxqkXMJrA5Dhk9LjvTuQOHyUwpxG4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
